---
title: "Interude : 수학에 관련된 표기법과 명제들"
#language: ../_language-ko_custom.yml 

number-sections: true
number-depth: 2
crossref:
  chapters: false
---

수치해석을 위해서는 기본적으로 미적분학과 선형대수학에 관련된 지식이 필요하다. 이 장은 문서에 걸쳐 사용될 표기법과 명제들을 점검하기 위한 것이다. 수학적 명제들은 학부 1-2 학년 수준의 미적분학과 선형대수학에 포함되는 내용이며 증명은 제시하지 않는다.  

</br>

## 기본적인 개념과 표기법 {#sec-basic_notations}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-notations}

#### 수

정수의 집합을 $\mathbb{Z}$ 라고 한다. 양의 정수의 집합을 $\mathbb{Z}_+$ 라고 하고 음의 정수의 집합을 $\mathbb{Z}_-$ 라고 한다. 유리수의 집합을 $\mathbb{Q}$ 라고 하고 실수의 집합을 $\mathbb{R}$, 복소수의 집합을 $\mathbb{C}$ 라고 한다. 실수의 집합과 복소수의 집합은 체(field) 라고 불리우는 사칙연산이 잘 정의되는 집합이다. 체는 $\mathbb{F}$ 로 표기한다.

:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-functions}

#### 함수

집합 $X$ 에서 $Y$ 로의 함수 $f$ 는 $f:X\to Y$ 라고 표기한다. $X$ 에서 $Y$ 로의 어떤 함수를 의미할때는 $X \mapsto Y$ 라고 표기한다. 

:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-kronecker_delta}

#### 크로네커 델타 함수

정수 $i, j$ 에 대해 

$$
\delta _{ij} = \left\{\begin{array}{ll} 1 \qquad &; \text{if } i = j, \\ 0 &; \text{if }i \ne j \end{array} \right.
$$

로 정의된 함수 $\delta_{ij}$ 를 크로네커 델타 함수라고 한다.
:::
:::


</br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-matrix}

#### 행렬

실수 성분을 갖는 $m \times n$ 행렬 전체의 집합을 $\mathcal{M}_{m\times n}(\mathbb{R})$ 이라고 한다. 복소수 성분을 갖는 $m \times n$ 행렬 전체의 집합을 $\mathcal{M}_{m \times n}(\mathbb{C})$ 라고 하며, 실수/복소수 여부가 일단 고정되기만 하면 상관 없는 경우 $\mathcal{M}_{m \times n}(\mathbb{F})$ 라고 한다. 행렬 $\boldsymbol{A}$ 의 $i$ 행 $j$ 열 성분은 $(\boldsymbol{A})_{ij}$ 혹은 $A_{ij}$ 와 같이 표기한다.

$n\times 1$ 행렬의 집합을 특히 $\mathcal{M}_n (\mathbb{F})$ 라고 한다. 실수/복소수 여부가 정해져 있을 경우 $\mathbb{F}$ 는 $\mathbb{R}$ 이나 $\mathbb{C}$ 가 된다. $\boldsymbol{v}\in \mathcal{M}_n (\mathbb{F})$ 의 $j$ 행 성분은 $v_j$ 로 표기한다. $\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $B_{ij} = A_{ji}$ 인 행렬 $\boldsymbol{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 를 $\boldsymbol{A}$ 의 **전치 행렬 (transposed matrix)** 이라고 하며 $\boldsymbol{A}^T$ 라고 쓴다. $\boldsymbol{A}=\boldsymbol{A}^T$ 일 때 $\boldsymbol{A}$ 를 **대칭 행렬(symmetric matrix)** 이라고 한다. $\boldsymbol{A}$ 가 복소행렬일 때 $C_{ij} = \overline{A_{ji}}$ 인 행렬 $\boldsymbol{C}$ 를 **수반 행렬 (adjoint matrix)** 라고 하며 $\boldsymbol{A}^\ast$ 라고 쓴다. $\boldsymbol{A}=\boldsymbol{A}^T$ 이면 **대칭 행렬** 이라고 하고 $\boldsymbol{A}=\boldsymbol{A}^\ast$ 이면 **에르미트 행렬(Hermitian matrix)** 이라고 한다.

:::
:::


</br>

이미 사용했지만 행렬은 $\boldsymbol{A}$ 와 같이 기울어진 굵은 글씨체 대문자로 표현한다. 열벡터, 즉 벡터의 행렬표현의 경우 $\boldsymbol{v}$ 와 같이 기울어진  굵은 글씨체의 소문자로 표현한다. 집합의 경우는 $X, A$ 와 같이 대문자를, 집합의 원소의 경우는 소문자를 사용한다. 학문적인 관례에 따르거나, 혹은 특별한 필요가 있을 경우 언급과 함께 이 원칙에 어긋날 수 있다.


</br>


## 행렬대수학 정리 {#sec-summary_of_linear_algebra}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-vector_space}
#### 벡터공간과 벡터

어떤 집합 $V$ 와 체 $\mathbb{F}$ 에 대해 $V$ 의 원소 사이의 덧셈과 $\mathbb{F}$ 와 $V$ 사이의 곱셈이 정의되어 있으며, 다음이 성립하면 $V$ 를 **$\mathbb{F}$ 위에서의 벡터공간** 혹은 **$\mathbb{F}$-벡터공간** 이라 한다.

1. $u,\,v \in V ,\, a\in \mathbb{F} \implies u+v = v+u \in V$, $av\in V$,

2. $u,\,v,\,w \in V,\, a,\, b\in \mathbb{F} \implies (u + v) + w = u+(v+w)$, $(ab)v = a(bv)$,

3. $\exists 0_V\in V\, \forall v\in V,\, v + 0_V=0_V+v = v$,

4. $\forall v\in V \;\exists w\in V$ s.t. $v + w = 0_V$,

5. $\forall v \in V \implies 1v =v$,

6.  $u,\,v \in V,\, a,\, b\in \mathbb{F} \implies a(u+v)=au + av,\, (a+b)v = av+bv$.

벡터공간 $V$ 가 정의되었을 때 벡터공간의 원소를 **벡터(vector)** 라 한다. $\mathbb{R}$ 위에서의 벡터 공간을 **실벡터공간(real vector space)** 혹은 **$\mathbb{R}$-벡터공간**, $\mathbb{C}$ 위에서의 벡터 공간을 **복소벡터공간(complex vector space)** 혹은 **$\mathbb{C}$-벡터공간** 이라 한다. $0_V$ 는 영벡터라고 불린다. 

:::
:::


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-linear_combinatio}

#### 선형 결합, 선형 독립, 기저

$\mathbb{F}$-벡터공간 $V$ 와 $v_1,\ldots,\,v_m\in V$ 에 대해 

$$
v = a_1v_1 + \cdots + a_mv_m ,\qquad a_1,\ldots,\,a_m\in \mathbb{F}
$$ {#eq-linear_combination}

일 때 $v$ 는 $\{v_1,\ldots,\,v_m\}$ 의 **선형 결합**이라고 한다. $\text{span}\, (v_1,\ldots,\,v_m)$ 은 $\{v_1,\ldots,\,v_m\}$ 의 선형결합인 모든 벡터의 집합이다. 즉, 

$$
\text{span}\, (v_1,\ldots,\,v_m) =\{a_1v_1 + \cdots + a_m v_m: a_1,\ldots,\,a_m\in \mathbb{F}\}
$$ {#eq-span_of_vectors}

이다. $\{v_1,\ldots,\,v_m\}$ 에 대해

$$
a_1v_1 + \cdots + a_m v_m = 0_V \implies a_1= \cdots =a_m=0
$$

일 때 $\{v_1,\ldots,\,v_m\}$ 이 **선형 독립** 이라고 한다. 선형 독립이 아닌 벡터의 집합을 **선형 종속** 이라고 한다.

$\{v_1,\ldots,\,v_m\}$ 이 선형 독립이며 $\text{span}\, (v_1,\ldots,\,v_m) = V$ 일 때 $\{v_1,\ldots,\,v_m\}$ 를 $V$ 의 **기저(basis)** 라고 한다. 유한개의 벡터로 이루어진 기저를 갖는 벡터공간을 **유한차원 벡터공간이**라고 한다. 유한차원 벡터공간이 아닌 벡터공간을 **무한차원 벡터공간**이라고 한다.

:::
:::

</br>



::: {#prp-dimension_of_vector_space}

벡터공간의 기저는 항상 찾을 수 있다. 또한 벡터공간의 기저는 유일하지 않다. 그러나 유한차원 벡터공간의 기저에 포함되는 벡터의 갯수는 정해져 있으며 이 갯수를 벡터공간의 **차원(dimension)** 이라고 한다. 벡터공간 $V$ 의 차원은 $\dim (V)$ 로 표기한다. $\dim(\mathcal{M}_n (\mathbb{F})) = n$ 이다.

:::

</br>

::: {#prp-uniqueness_of_coefficients}

벡터공간 $V$ 의 기저 $\mathcal{B}_V = \{v_1,\ldots,\,v_m\}$ 에 대해 벡터 $v\in V$ 를 $\mathcal{B}_V$ 의 선형결합으로 표현하는 방법은 유일하다. 


:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-subspace}
$U$ 가 벡터공간 $V$ 의 부분집합이며 벡터공간일 때 $U$ 를 $V$ 의 **부분공간**이라고 한다.

:::
:::

</br> 

::: {#prp-dimension_of_subspaces}

$U$ 가 유한차원 벡터공간 $V$ 의 부분부분공간이면 $U$ 도 유한차원 벡터공간이며 $\dim (U) \le \dim (V)$ 이다. $\dim (U)= \dim (V)$ 이면 $U=V$ 이다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-linear_map}

$\mathbb{F}$-벡터공간 $U,\,V$ 에 대해 함수 $T:U \to F$ 가 다음을 만족하면 **선형 사상(linear map)** 이라고 한다.

$$
\forall u_1,\,u_2\in U,\, \forall c\in \mathbb{F}, \qquad T(u_1+cu_2) =  T(u_1)+cT(u_2).
$$

$U \mapsto V$ 선형 사상의 집합을 $\mathcal{L}(U, V)$ 라고 표기한다. 자기 자신으로의 선형사상을 **선형 연산자 (linear operator)** 라고 하고 $\mathcal{L}(U)$ 처럼 표현한다.
:::
:::


</br>

::: {#prp-linear_operators_are_vector_space}

#### 선형연산자의 합과 스칼라곱

$\mathbb{F}$-벡터공간 $U,\,V$ 에서의 선형사상의 집합 $\mathcal{L}(U, V)$ 에 더하기와 스칼라곱 연산을 다음과 같이 정의한다. $T,\,S\in \mathcal{L}(U, V)$ 이고 $c\in \mathbb{F}$ 일 때 $u\in U$ 에 대해

$$
\begin{aligned}
(T+S)(u) &= T(u)+S(u), \\
(cT)(u) & =  c(T(u)).
\end{aligned}
$$

이렇게 정의된 연산에 대해 $\mathcal{L}(U, V)$ 는 벡터공간이다.

:::

</br>

::: {#prp-composition_of_linear_map}

$S\in \mathcal{L}(U, V)$, $T\in \mathcal{L}(V, W)$ 일 때 선형사상의 합성 $T \circ S$ 도 선형사상이다.

:::

</br>

::: {#prp-uniqueness_of_linear_map}

$T\in \mathcal{L}(U, V)$ 는 $U$ 의 어떤 기저 $\{u_1,\ldots,\,u_m\}$ 에 대해 $T(u_1)=v_1, \ldots,\,T(u_m)=v_m$ 을 만족하는 선형사상은 유일하다.  

:::

</br>

::: {#prp-form_of_linear_map}

$T\in \mathcal{L}(U, V)$ 일 때 $n=\dim (U), m = \dim (V)$ 라고 하자. $\{u_1,\ldots,\,u_n\}$ 이 $U$ 의 기저이고 $\{v_1,\ldots,\,v_m\}$ 이 $V$ 의 기저일 때 선형사상 $T$ 는 $u_i$ 에 대해 항상

$$
T (u_i) =  A_{1i}v_1 + \cdots + A_{mj}v_m  = \sum_{j=1}^m A_{ji}v_j, \qquad i=1,\ldots, n
$$ {#eq-linear_map_for_basis}

꼴이다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-matrix_represenation_of_vectors_and_linear_map}

#### 벡터와 선형 사상의 행렬 표현
$T\in \mathcal{L}(U, V)$ 이고 $\mathcal{B}_U = \{u_1,\ldots,\,u_m\}$ 과 $\mathcal{B}_V = \{v_1,\ldots,\,v_n\}$ 이 각각 $U$ 와 $V$ 의 기저라고 하자. $u = a_1 u_1 + a_m u_m$ 일 때 $u$ 를 $m \times 1$ 행렬로 $\begin{bmatrix} a_1 & \cdots & a_m\end{bmatrix}^T$ 와 같이 $m \times 1$ 행렬로 표현하는 것을 $u$ 의 $\mathcal{B}_U$ 기저에 대한 행렬 표현이라고 하며 $[u]_{\mathcal{B}_U}$ 로 표기한다. 역시 $v= b_1 v_1 + \cdots + b_n v_n$ 일 때 $[v]_{\mathcal{B}_V} = \begin{bmatrix}b_1 & \cdots & b_n\end{bmatrix}^T$ 이다. 

$T$ 는 $\mathcal{B}_U,\,\mathcal{B}_V$ 에 대해 @eq-linear_map_for_basis 와 같이 정의되므로 행렬 형태로 쓸 수 있으며 이것을 $[T]_{\mathcal{B}_U, \mathcal{B}_V}$ 라고 표기한다. 즉 $([T]_{\mathcal{B}_U, \mathcal{B}_V})_{ij} = A_{ij}$ 이다. 

:::
:::


</br>

::: {#prp-uniqueness_of_matrix_representaiton}

정해진 기저에 대해 벡터와 선형사상의 행렬표현은 유일하다.

:::

</br>

::: {#prp-isomorphism_for_vector_space}

@def-matrix_represenation_of_vectors_and_linear_map 의 정의, 표기법과 일반적인 행렬의 합과 스칼라곱, 행렬간 곱 연산에 대해

$$
T(u) =v \iff [T]_{\mathcal{B}_U, \mathcal{B}_V} [u]_{\mathcal{B}_U} = [v]_{\mathcal{B}_V}
$$

가 성립한다. $T,\,S\in \mathcal{L}(U, V)$, $u_1,\,u_2\in U$, $c\in \mathbb{F}$ 에 대해

$$
\begin{aligned}
T(u_1+cu_2) = v &\iff [T]_{\mathcal{B}_U,\mathcal{B}_V}[u_1]_{\mathcal{B}_U} + c[T]_{\mathcal{B}_U,\mathcal{B}_V}[u_2]_{\mathcal{B}_U} = [v]_{\mathcal{B}_V}, \\
(T+cS)(u) = v &\iff ([T]_{\mathcal{B}_U,\mathcal{B}_V}+c[S]_{\mathcal{B}_U,\mathcal{B}_V})[u]_{\mathcal{B}_U} = [v]_{\mathcal{B}_V}, \\
\end{aligned}
$$

가 성립한다. $T\in \mathcal{L}(U, V),\, S\in \mathcal{L}(V, W)$ 이고 $\mathcal{B}_U,\, \mathcal{B}_V,\, \mathcal{B}_W$ 가 각각 $U, V, W$ 의 기저 일 때,

$$
(S \circ T)(u) = w \iff [S]_{\mathcal{B}_V, \mathcal{B}_W} [T]_{\mathcal{B}_U, \mathcal{B}_V} [u]_{\mathcal{B}_U} = [w]_{\mathcal{B}_W}
$$

가 성립한다.

:::

<br>


::: {#prp-isomorphism}

두 벡터공간 사이에 전단사 함수가 존재할 때 두 벡터공간이 **동형 (isomorphic)** 이라고 하며, 두 벡터공간 사이의 전단사 함수를 **동형 사상(isomorphism)** 이라고 한다. 두 벡터공간 $U,\,V$ 가 동형일 때 $U\cong V$ 로 표현한다. 

($1$) 유한차원 벡터공간 $U,\,V$ 에 대해 다음이 성립한다.

$$
U \cong V \iff \dim(U) = \dim (V).
$$

($2$) $n$ 차원 $\mathbb{F}$-벡터공간과 $\mathcal{M}_n (\mathbb{F})$ 는 동형이다. 

($3$) $n$ 차원 $\mathbb{F}$-벡터공간 $U$ 와 $m$ 차원 $\mathbb{F}$-벡터공간 $V$ 사이의 선형사상의 집합 $\mathcal{L}(U, V)$ 와 $\mathcal{M}_{m \times n}(\mathbb{F})$ 는 동형이다.

:::

</br>


::: {#prp-fundamental_theorem_of_linear_algebra}

벡터와 선형사상은 그 행렬 표현과 본질적으로 같다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-kernel_image_rank_nullity}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $\ker (\boldsymbol{A})$, $\text{im}\, (\boldsymbol{A})$, $\text{rank}\, (\boldsymbol{A})$, $\text{nuliity}(\boldsymbol{A})$ 는 다음과 같이 정의된다.

$$
\begin{aligned}
\ker (\boldsymbol{A}) &= \{\boldsymbol{v}\in \mathcal{M}_n(\mathbb{F}) : \boldsymbol{Av}=\boldsymbol{0} \}, \\
\text{im}\, (\boldsymbol{A}) &= \{\boldsymbol{Av}: \boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})\}, \\
\text{rank}\, (\boldsymbol{A}) &= \dim (\text{im}\, (\boldsymbol{A})), \\
\text{nullity}\, (\boldsymbol{A}) & = \dim (\ker (\boldsymbol{A})).
\end{aligned}
$$
:::
:::

</br>

::: {#prp-kernel_image_subspace}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $\ker (\boldsymbol{A})$ 는 $\mathcal{M}_n (\mathbb{F})$ 의 부분공간이며 $\text{im}\, (\boldsymbol{A})$ 는 $\mathcal{M}_{m}(\mathbb{F})$ 의 부분공간이다. 또한 다음이 성립한다.

$$
\dim (\mathcal{M}_m(\mathbb{F})) = \text{rank}\, (\boldsymbol{A}) + \text{nullity}\, (\boldsymbol{A}).
$$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-determinant}
#### 행렬식

행렬식 $\det :\mathcal{M}_{n \times n}(\mathbb{F}) \to \mathbb{F}$ 은 다음과 같이 정의된 함수이다. [@eq-determinant_of_matrix 에 관한 사항들은 선형대수학 책을 참고하라]{.aside}

$$
\det(\boldsymbol{A}) = \sum_{\sigma \in S_n} \text{sgn}(\sigma)\left(\prod_{i=1}^n A_{i\sigma(i)}\right)
$$ {#eq-determinant_of_matrix}

:::
:::

</br>

::: {#prp-properties_of_determinant}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 와 $c\in \mathbb{F}$ 에 대해 다음이 성립한다.

&emsp; ($1$) $\boldsymbol{A}$ 의 서로 다른 두 행이나 두 열의 위치를 바꾼 행렬을 $\boldsymbol{A}_1$ 이라 할 때 $\det(\boldsymbol{A}_1) = -\det (\boldsymbol{A})$ 이다.

&emsp; ($2$) $\boldsymbol{A}$ 의 한 행 혹은 한 열에 상수 $c$ 가 곱해진 행렬을 $\boldsymbol{A}_2$ 라 할 때 $\det(\boldsymbol{A}_2) = c\det(\boldsymbol{A})$ 이다.

&emsp; ($3$) $\boldsymbol{A}$ 의 한 행이 다른 행의 상수곱이거나 한 열이 다른 열의 상수곱이면 $\det (\boldsymbol{A}) = 0$ 이다.

&emsp; ($4$) $\det(\boldsymbol{A}^T) = \det(\boldsymbol{A})$ 이다.

&emsp; ($5$) $\det(\boldsymbol{AB}) = \det(\boldsymbol{A}) \det(\boldsymbol{B})$ 이다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-inverse_matrix}

#### 항등행렬과 역행렬

$n \times n$ 행렬을 **정사각 행렬(square matrix)** 이라고 한다. $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 $A_{ii}=1$, $(i=1,\ldots,\,n)$ 이며 나머지 성분이 $0$ 일 때 **항등 행렬 (Identity matrix)** 라고 하며 $\boldsymbol{I}_n$ 으로 표기한다. 행렬의 크기를 구체적으로 표기할 필요가 없을 때는 $\boldsymbol{I}$ 라고 표기한다.

$\boldsymbol{X}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 에 대해 어떤 행렬 $\boldsymbol{Y}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 존재하여 $\boldsymbol{XY}=\boldsymbol{YX}=\boldsymbol{I}_n$ 일 때 $\boldsymbol{Y}$ 를 $\boldsymbol{X}$ 의 **역행렬 (inverse matrix)** 라고 하며 행렬 $\boldsymbol{A}$ 의 역행렬은 $\boldsymbol{A}^{-1}$ 로 표기한다. 역행렬이 존재하는 행렬을 **가역 행렬** 이라고 한다.
:::
::: 

</br>

::: {#prp-properties_of_inverse_matrix}

$\boldsymbol{A},\,\boldsymbol{B}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 와 $c\in \mathbb{F}$ 에 대해 다음이 성립한다.

&emsp; ($1$) $(\boldsymbol{A}^{-1})^{-1} =\boldsymbol{A}$,

&emsp; ($2$) $(c\boldsymbol{A})^{-1} = \dfrac{1}{c} \boldsymbol{A}^{-1}$,

&emsp; ($3$) $(\boldsymbol{AB}^{-1}) =\boldsymbol{B}^{-1}\boldsymbol{A}^{-1}$.

&emsp; ($4$) $\det(\boldsymbol{A}^{-1}) = \dfrac{1}{\det (\boldsymbol{A})}$
:::


</br>

::: {#prp-determinant_and_inverse_matrix}

정사각 행렬 $\boldsymbol{A}$ 가 가역행렬일 필요충분조건은 $\det (\boldsymbol{A}) \ne 0$ 이다.
:::

</br>

::: {#prp-similar_matrix}

$\boldsymbol{A} \in \mathcal{M}_{m\times n}(\mathbb{F})$ 과 $\boldsymbol{x}\in \mathcal{M}_n (\mathbb{F})$, $\boldsymbol{y} \in \mathcal{M}_m (\mathbb{F})$, 그리고 가역행렬 $\boldsymbol{S}\in \mathcal{M}_{m \times m} (\mathbb{F})$ 에 대해 다음이 성립한다.

$$
\boldsymbol{Ax}=\boldsymbol{y} \iff \boldsymbol{SAx} = \boldsymbol{Sy}
$$

:::


</br>

::: {#prp-invertible_matrix_basis_transform}

$\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_n \}$ 가 $\mathcal{M}_n(\mathbb{F})$ 의 기저이며 $\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 가역이면 $\{\boldsymbol{Pv}_i : i=1,\ldots,\,n\}$ 도 $\mathcal{M}_n(\mathbb{F})$ 의 기저이다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-similar_matrix}

두 정사각 행렬 $\boldsymbol{A},\, \boldsymbol{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 어떤 가역 행렬 $\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 존재하여 $\boldsymbol{A}= \boldsymbol{PBP}^{-1}$ 일 때 두 행렬을 **닮은 행렬** 이라고 한다. 행렬 $\boldsymbol{A}$ 와 가역행렬 $\boldsymbol{P}$ 에 대해 $\boldsymbol{PAP}^{-1}$ 로 바꾸는 것을 **닮음 변환 (similar transform)** 이라고 한다.

:::
:::

</br>

::: {#prp-similar_transform}

닮음 변환은 기저의 변환이다. $\mathcal{B} = \{u_1,\ldots,\,u_n\}$, 가 벡터공간 $U$ 의 기저라고 하고 $T\in \mathcal{L}(U)$ 에 대해 $[T]_{\mathcal{B}} = \boldsymbol{A}$ 라고 하자. $[u_i]_{\mathcal{B}}= \hat{\boldsymbol{e}}_i$ 이다. $U$ 의 다른 기저 $\mathcal{B}' = \{u_1', \ldots,\, u_n'\}$ 에 대해 $\boldsymbol{p}_i = [u'_i]_{\mathcal{B}}$ 를 $i$ 번째 열벡터로 갖는 행렬을 $\boldsymbol{P}$ 라고 하자. 이 때 $\boldsymbol{PAP}^{-1} = [T]_{\mathcal{B}'}$ 이다. 
 

:::

</br> 

::: {.callout-note appearance="simple" icon="false"}
::: {#def-innerproduct_space}

#### 내적과 노름

$\mathbb{F}$ 벡터공간 $V$ 에서 다음을 만족하는 함수 $\langle \,, \,\rangle : V \times V \to \mathbb{F}$ 를 **내적(inner product)** 이라고 한다.

&emsp; ($1$) $\langle v,v\rangle \ge 0$, 

&emsp; ($2$) $\langle v,v \rangle = 0 \iff v=0_V$,

&emsp; ($3$) $\langle u + u',v\rangle = \langle u, u\rangle + \langle u', u\rangle$, $\langle u, v + v'\rangle = \langle u, v\rangle + \langle u, v'\rangle$, 

&emsp; ($5$) $c\in \mathbb{F}$ 에 대해 $\langle cu,v\rangle = c\langle u, v\rangle$, $\langle u, cv\rangle = \overline{c} \langle u, v\rangle$, 

&emsp; ($6$) $\langle u, v\rangle = \overline{\langle v, u\rangle}$. $\mathbb{R}$-내적벡터공간인 경우 $\langle u, v\rangle =\langle v, u\rangle$

내적이 부여된 벡터공간을 **내적벡터공간** 이라고 한다. 두 백터의 내적이 $0$ 일 때 두 벡터는 서로 **직교한다(perpendicular, orthogonal)** 라고 한다. 



내적벡터 공간에서 **거리함수(노름, norm)** $\|\, \|:V \to [0, \infty)$ 를 

$$
\|v\|=\sqrt{\langle v, v\rangle}
$$ {#eq-norm_in_innerproduct_space}

로 정의 할 수 있다.

:::
:::


</br>

::: {#prp-properties_of_norm}

$\mathbb{F}$-내적벡터공간의 거리 함수에 대해 다음이 성립한다.

&emsp; ($1$) $\|v\|\ge 0$, 

&emsp; ($2$) $\|v\|=0 \iff v=0_V$,

&emsp; ($3$) $c \in \mathbb{F}$ 에 대해 $\|cv\|= |c|\|v\|$,

&emsp; ($4$) $\|u+v\| \le \|u\| + \|v\|$.
:::


</br>

::: {#prp-properties_of_norm}

$\mathbb{F}$-내적벡터공간의 내적과 거리함수에 대해 다음이 성립한다.

&emsp; ($1$) 피타고라스 정리 : $\langle u,v\rangle = 0 \iff \|u+v\|^2 = \|u\|^2 + \|v\|^2$, 

&emsp; ($2$) 코시-슈바르츠 부등식 : $| \langle u,v\rangle | \le \|u\| \|v\|$, 

&emsp; ($3$) 삼각부등식 : $\|u+ v\| \le \|u\| + \|v\|$, 

&emsp; ($4$) 평행사변형 공식 : $\|u+v\|^2 + \|u-v\|^2 = 2\|u\|^2 + 2\|v\|^2$.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-eigenspace}

#### 고유값, 고유벡터, 고유공간
행렬 $\boldsymbol{A}\in \mathcal{m \times n}(\mathbb{F})$ 에 대해 $\boldsymbol{Av}=\lambda \boldsymbol{v}$ 를 만족하는 $\lambda \in \mathbb{F}$ 와 $\boldsymbol{0}$ 이 아닌 $\boldsymbol{v}\in \mathcal{M}_n (\mathbb{F})$ 가 존재할 때 $\lambda$ 를 $\boldsymbol{A}$ 의 **고유값 (eigen value)** 이라고 하고 $\boldsymbol{v}$ 를 고유값 $\lambda$ 에 대한 $\boldsymbol{A}$ 의 **고유 벡터 (eigne vector)** 라고 한다. 고유값 $\lambda$ 를 갖는 고유벡터의 집합과 $\{\boldsymbol{0}\}$ 의 합집합을 고유값 $\lambda$ 에 대해 $\boldsymbol{A}$ 의 **고유 공간 (eigenspace)** 라고 하며, $E(\lambda, \boldsymbol{A})$ 라고 표기한다.

:::
:::

</br>

::: {#def-characteristic_polynomial}

#### 특성다항식

정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $p_\boldsymbol{A}(\lambda) = \det(\lambda \boldsymbol{I}_n -\boldsymbol{A})$ 는 $\lambda$ 에 대한 $n$-차 다항식으로 행렬 $\boldsymbol{A}$ 의 **특성다항식 (characteristic polynomial)** 이라 한다. 

:::


</br>

::: {#prp-characteristic_polynomial_and_eigenvalue}

$\lambda \in \mathbb{F}$ 가 $\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 의 고유값이기 위한 필요충분조건은 $p_{\boldsymbol{A}}(\lambda) =  0$ 인 것이다. 

:::

</br>

::: {#prp-eigenvlaues_in_complex_field}

복소수체에서 정의된 정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{C})$ 에 대한 고유값이 항상 존재한다.

:::


</br>

::: {#prp-eigenvectors_with_different_eigenvalues_are_orthogonal}

$\mathbb{F}$-내적 벡터 공간에서 서로 다른 고유값을 갖는 고유벡터들의 집합은 선형독립이다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-orthonormal_basis}

#### 정규직교기저와 표준기저

$\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_n\}$ 이 벡터공간 $V$ 의 기저이며 $\langle \boldsymbol{v}_i,\,\boldsymbol{v}_j\rangle = \delta_{ij}$ 일 때 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_n\}$ 를 $V$ 의 **정규직교기저 (orthonormal basis)** 라고 한다. 벡터공간 $\mathcal{M}_n(\mathbb{F})$ 에 대해 $\hat{\boldsymbol{e}}_i \in \mathcal{M}_n (\mathbb{F})$ 를 $(\hat{\boldsymbol{e}}_i)_j = \delta_{ij}$ 로 정의하자. 이 때 $\{\hat{\boldsymbol{e}}_1, \ldots, \hat{\boldsymbol{e}}_n\}$ 는 $\mathcal{M}_n(\mathbb{F})$ 의 정규직교기저이며 특히 **표준 기저 (standard basis)** 라고 한다.

:::
:::

</br>



::: {#prp-coefficients_of_vector_in_innerproduct_space}

$\mathbb{F}$-벡터공간 $V$ 의 정규직교기저 $\mathcal{B}_V = \{v_1,\ldots,\,v_n\}$ 에 대해 $v=\sum_{i} a_i v_i$ 라면 $a_i = \langle v,\,v_i\rangle$ 이다. 즉, 

$$
v = \sum_{i} \langle v,\, v_i\rangle v_i
$$

이다. 

:::

</br>

::: {#prp-orthonormal_basis}

유한차원 내적벡터공간에서는 기저로부터 항상 정규직교기저를 얻을 수 있다. 그중 한 가지 방법이 그람-슈미트(Gram-Schmidt) 방법이다

:::

</br>

::: {#prp-schure_theorem}

#### 슈어 정리 (Schur’s Theorem)

유한차원 $\mathbb{C}$-내적벡터공간 $V$ 에서 정의된 연산자 $T\in \mathcal{L}(V)$ 는 어떤 정규직교기저에서 상삼각 행렬로 표현된다.

:::

</br>

::: {#prp-innerproduct_in_orthonormal_basis}

$\mathbb{R}$-내적공간 $V$ 의 정규직교 기저 $\mathcal{B}_V$ 에 대한 벡터 $u, v$ 의 행렬표현 $\boldsymbol{u} = [u]_{\mathcal{B}_V},\, \boldsymbol{v} = [v]_{\mathcal{B}_V}$ 에 대해 $\langle u, v\rangle = \boldsymbol{v}^T\boldsymbol{u}$ 이다. $V$ 가 $\mathbb{C}$-내적공간일 경우 $\langle u, v\rangle = \boldsymbol{v}^\ast\boldsymbol{u}$ 이다.


:::

</br>

::: {#prp-inner_product_and_adjoint_matrix}

$\boldsymbol{u},\,\boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})$, $\boldsymbol{A} \in \mathcal{M}_{n \times n}(\mathbb{F})$ 와 $\boldsymbol{A}$ 의 수반행렬 $\boldsymbol{A}^\ast$ 에 대해 다음이 성립한다.

$$
\langle \boldsymbol{Au}, \boldsymbol{v}\rangle = \langle \boldsymbol{u}, \boldsymbol{A}^\ast \boldsymbol{v}\rangle
$$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-isometry}

$\boldsymbol{S}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 모든 $\boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})$ 에 대해 $\|\boldsymbol{Sv}\| = \|\boldsymbol{v}\|$ 이면 $\boldsymbol{S}$ 를 **Isometry** 라고 한다. $\mathbb{F} =\mathbb{R}$ 일 때 **직교 행렬(orthogonal matrix)** 이라고 하며 $\mathbb{F}=\mathbb{C}$ 일 때 **유니타리 행렬(unitary matrix)** 라고 한다. 직교 행렬에 의한 닮음변환을 **직교 변환 (orthogonal transformation)** 이라고 하며, 유니타리 행렬에 의한 닮음변환을 **유니타리 변환 (unitary transformation)** 이라고 한다.
:::
:::

</br>

::: {#prp-properties_of_isometry}

$\boldsymbol{S}$ 가 Isometry 일 때 다음이 성립한다.

&emsp; ($1$) $\{\boldsymbol{v}_1,\ldots,\boldsymbol{v}_n\}$ 이 정규직교기저일 때 $\{\boldsymbol{Sv}_1,\ldots,\boldsymbol{Sv}_n\}$ 도 정규직교기저이다.

&emsp; ($2$) $\boldsymbol{S}^{-1}= \boldsymbol{S}^\ast$ 이다. 따라서 $\boldsymbol{O}$ 가 직교행렬이면 $\boldsymbol{O}^{-1}=\boldsymbol{O}$ 이다. 

&emsp; ($3$) 두 isometry 의 곱은 isometry 이다.

:::


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-normal_matrix}

정사각 행렬 $\boldsymbol{A} \in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 $\boldsymbol{AA}^\ast = \boldsymbol{A}^\ast\boldsymbol{A}$ 일 때 이 행렬을 **정규 행렬 (normal matrix)** 라고 한다.

:::
:::

</br>

::: {#prp-properties_of_normal_matrix}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 정규행렬일 때 다음이 성립한다.

&emsp; ($1$) $\boldsymbol{A}$ 가 정규행렬일 필요충분조건은 모든 $\boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})$ 에 대해 $\|\boldsymbol{Av}\|=\|\boldsymbol{A}^\ast\boldsymbol{v}\|$ 이다. 

&emsp; ($2$) $\boldsymbol{v}$ 가 공유값 $\lambda$ 를 갖는 $\boldsymbol{A}$ 의 고유벡터이면 고유값 $\overline{\lambda}$ 를 갖는 $\boldsymbol{A}^\ast$ 의 고유벡터이다.

&emsp; ($3$) 서로 다른 고유값을 갖는 $\boldsymbol{A}$ 의 고유벡터는 직교한다.

&emsp; ($4$) $\boldsymbol{A}$ 가 복소행렬일 때 상삼각행렬 꼴은 대각행렬이다.$^\ast$[$^\ast$ 슈어 정리 에 의해 항상 상삼각 행렬 꼴로 표현할 수 있음을 안다.]{.aside}

:::


</br>

::: {#prp-properties_of_hermitian_matrix}

#### 복소수체에서 정의된 행렬의 스펙트럼 정리

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{C})$ 일 때 $\boldsymbol{A}^\ast = \boldsymbol{A}$ 인 행렬을 에르미트 행렬이라고 한다. 에르미트 행렬은 정규행렬이다. 에르미트 행렬에 대해 다음이 성립한다.

&emsp; ($1$) 에르미트 행렬의 고유값은 실수이다.

&emsp; ($2$) 서로 다른 고유값을 갖는 에르미트 행렬의 고유벡터는 직교한다. 

&emsp; ($3$) 에르미트 행렬의 고유벡터로 정규직교기저를 구성 할 수 있다.

&emsp; ($4$) 에르미트 행렬은 유니타리 변환에 의해 대각행렬이 된다. 이 대각행렬의 대각성분이 고유값이다.

:::

</br>

::: {#prp-properties_of_hermitian_matrix}

#### 실수체에서 정의된 행렬의 스펙트럼 정리 

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{R})$ 일 때 $\boldsymbol{A}^T= \boldsymbol{A}$ 인 행렬을 대칭 행렬이라고 한다. 대칭행렬은 정규행렬이다. 대칭행렬에 대해 다음이 성립한다.

&emsp; ($1$) 서로 다른 고유값을 갖는 대칭행렬의 고유벡터는 직교한다.

&emsp; ($3$) 대칭행렬의 고유벡터로 정규직교기저를 구성 할 수 있다.

&emsp; ($4$) 직교행렬은 직교 변환에 의해 대각행렬이 된다. 이 대각행렬의 대각성분이 고유값이다.

:::


</br>


## 일변수 미적분학 정리 {#sec-summary_of_one_variable_calculus}

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-open_closed_interval}

$a<b$ 일 때 아래와 같이 정의된 $(a, b)$ 와 $[a, b]$ 를 각각 **열린 구간 (open interval)**, **닫힌 구간 (closed interval)** 이라 한다.

$$
\begin{aligned}
(a, b) & = \{x\in \mathbb{R} : a<x<b\}, \\
[a, b] & = \{x \in \mathbb{R} : a \le x \le b\}. 
\end{aligned}
$$

:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-bounded}

실수의 집합 $X$ 에 대해 어떤 $M\in \mathbb{R}$ 이 존재하여 $x\in X \implies x \le M$ 일 때 $X$ 는 **위로 유계** 라고 한다. 어떤 $m\in \mathbb{R}$ 이 존재하여 $x\in X \implies x \ge m$ 일 때 $X$ 는 **아래로 유계** 라고 한다. $X$ 가 위로도 아래로도 유계이면 **유계** 라고 한다.

:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-sequence}

집합 $A$ 에 대해 양의 정수 $\mathbb{Z}_+$ 에서 $A$ 로의 함수를 **수열 (sequence)** 라고 한다. $a:\mathbb{Z}_+ \to A$ 일 때 $a(n)$ 을 관례적으로 $a_n$ 이라고 쓰며 $\langle a_n \rangle$ 은 $(a_1,\,a_2,\ldots,)$ 를 의미한다.

:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-limit_of_sequence}

#### 수열의 극한 {#sec-limit_of_series}

수열 $\langle a_n\rangle = (a_1,\,a_2,\ldots)$ 이 $a$ 로 수렴한다는 것은 임의의 실수 $\epsilon>0$ 에 대해 어떤 자연수 $N$ 이 존재하여

$$
n>N \implies |a_n -a |<\epsilon
$$

을 만족하는 것이며, $(a_n)$ 이 $a$ 로 수렴 할 때

$$
\lim_{n\to \infty} a_n = a
$$

라 표기한다. 수열이 수렴하지 않을 때는 발산한다라고 한다.
:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-continuity_of_function}

#### 함수의 극한과 연속성 {#sec-limit_and_continuity_of_function}

함수 $f:X\subset \mathbb{R} \to \mathbb{R}$ 을 생각하자. 함수 $f$ 가 $x_0 \in X$ 에서 $L$ 로 수렴한다는 것은 임의의 $\epsilon>0$ 에 대해 어떤 $\delta>0$ 이 존재하여

$$
|x-x_0 |< \delta \implies |f(x)-L|< \epsilon
$$

인 것이다. 이 때,

$$
\lim_{x \to x_0} f(x) = L
$$

이라 쓴다. 만약

$$
\lim_{x \to x_0} f(x) = f(x_0)
$$

이면 $f$ 는 $x_0$ 에서 연속이라고 하며, $f$ 가 모든 $x\in X$ 에 대해 연속일 때 $f$ 를 연속함수라 한다. 어떤 구간 $I$ 에서 연속인 함수의 집합을 $C_I$ 라고 쓴다. 특별히 닫힌 구간 $[a,\,b]$ 에서 정의된 함수 $f$ 에 대해 $f$ 가 $(a,\,b)$ 에서 연속이며 $\lim_{x\to a+} f(x)=f(a)$ 이고 $\lim_{x \to b-} f(x) = f(b)$ 이면 $f$ 는 $[a,\,b]$ 에서 연속이라고 한다.
:::
:::

</br>

::: {#prp-maximum_minimum}

#### 최대최소정리 {#sec-theorem_minimum_maximum}

함수 $f$ 가 닫힌 구간 $[a,\,b]$ 에서 연속이라면 $\{f(x):x\in [a,\,b]\}$ 는 최소값과 최대값을 가진다.

:::
</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-differentiability_of_function}

#### 함수의 미분 {#sec-differentiation}

함수 $f:X\subset \mathbb{R} \to \mathbb{R}$ 에 대해 $x_0$ 에서 미분가능하다는 것은 극한

$$
\lim_{h \to 0}\dfrac{f(a+h)-f(a)}{h}
$$

이 존재한다는 것이며 위의 극한값을 $f'(a)$ 라고 쓴다. 함수 $f$ 가 모든 $x\in X$ 에 대해 미분 가능 할 때 $f$ 를 미분가능함수라고 한다. 
:::
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-high_order_differentiation}

#### 도함수 {#sec-derivative}

함수 $f:X \subset \mathbb{R} \to \mathbb{R}$ 이 미분 가능 할 때 $f'(x)$ 는 $X$ 에서 정의된 함수이며 이를 $f$ 의 도함수 혹은 1차 도함수라고 한다. $f'(x)$ 가 미분가능한 함수 일 때 $f'(x)$ 의 도함수를 $f''(x)$ 혹은 $f^{(2)}(x)$ 라고 쓰며 $f$ 의 2차 도함수라고 한다. 같은 방법으로 $f$ 함수에 대한 $n$ 차 도함수를 정의할 수 있으며 $f^{(n)}(x)$ 라고 쓴다. 여러 차수의 도함수를 나열할 경우 원래의 함수를 $f^{(0)}$, 1 차 도함수를 $f^{(1)}$ 로 쓴다. 
:::
:::
</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-Cn_class_function}

#### $C^n_I$ {#sec-class_of_functions}

구간 $I$ 에서 $n$ 번 미분 가능하며, 그 $n$ 차 도함수가 연속인 함수의 집합을 $C^n_I$ 라고 한다. 구간이 실수 전체일 경우는 $C^n$ 이라고 한다. $e^x$ 함수의 경우와 같이 실수 전체 영역에서 무한번 미분 가능한 함수의 집합을 $C^{\infty}$ 라고 한다.

:::
:::

</br>

::: {#prp-roll_theorem}
#### 롤의 정리 (Roll's theorem) {#sec-roll_theorem}

$f\in C[a,\,b]$ 이고 $f$ 가 $(a,\,b)$ 구간에서 미분가능하다고 하자. $f(a)=f(b)$ 이면 $f'(c)=0$ 을 만족하는 $c\in (a,\,b)$ 가 존재한다.

:::

</br>

::: {#prp-generalized_roll_theorem}

#### 일반화된 롤의 정리 {#sec-generalized_roll_theorem}

$f\in C^{n-2}[a,\,b]$ 이고 $f$ 가 $(a,\,b)$ 구간에서 $n-1$ 번 미분 가능하며 $n$ 개의 서로 다른 $x_1,\ldots,\,x_n$ 에서 $f(x_i)=0$ 일 때, $f^{(n-1)}(\xi) = 0$ 인 $\xi\in (a,\,b)$ 가 존재한다.

:::

</br>

::: {#prp-intermediate_value_theorem}

#### 중간값 정리 (Intermediate value theorem) {#sec-intermediate_value_theorem}

$[a,\,b]$ 를 포함하는 구간에서 연속인 함수 $f:X\to \mathbb{R}$  에 대해 $d$ 가 $f(a)$ 와 $f(b)$ 사이의 값이면, 즉 $f(a)< d < f(b)$ 이거나 $f(b)<d <f(a)$ 라면
$$
f(c) = d
$$

인 $c$ 가 $(a,\,b)$ 안에 항상 존재한다.
:::

</br>

::: {#prp-intermediate_value_for_many_points} 

#### 따름정리 : 여러 점의 경우 {#sec-intermediate_value_theorem_for_many_points}

$[a,\,b]$ 를 포함하는 구간에서 연속인 함수 $f:X \to \mathbb{R}$ 에 대해 $\{x_1,\ldots,\,x_n\}\subset [a,\,b]$ 일 때

$$
f(c) = \dfrac{f(x_1)+ \cdots + f(x_n)}{n}
$$

을 만족하는 $c\in [a,\,b]$ 가 항상 존재한다.

:::

</br>

::: {#prp-mean_value_theorem}
#### 평균값 정리 (Mean value theorem) {#sec-mean_value_theorem}

함수 $f:X \subset\mathbb{R} \to \mathbb{R}$ 이 $[a,\,b]$ 를 포함하는 구간에서 에서 연속이고, $(a,\,b)$ 에서 미분 가능하면
$$
\dfrac{f(b)-f(a)}{b-a}=f'(c)
$$

를 만족하는 $c\in (a,\,b)$ 가 존재한다.
:::

</br>

::: {#prp-taylor_theorem_for_single_variable}
#### 일변수 함수에 대한 테일러 정리 {#sec-tayler_theorem}

$a$ 를 포함하는 열린구간 $I$ 에서 정의된 함수 $f:I \to \mathbb{R}$ 가 $n+1$ 번 미분 가능한 함수일 때 임의의 $x\in I$ 에 대하여

$$
f(x) = \sum_{k=0}^{n} \dfrac{f^{(k)}(a)}{k!} (x-a)^k + \dfrac{f^{(n+1)}(\xi)}{(n+1)!}(x-a)^{n+1}
$$

을 만족하는 $\xi \in I$ 가 존재한다. 이 때 $\displaystyle \sum_{k=0}^{n} \dfrac{f^{(k)}}{k!} (x-a)^k$ 를 $n$ 차 테일러 다항식이라고 하며, $\displaystyle \dfrac{f^{(n+1)}(\xi)}{(n+1)!}(x-a)^{n+1}$ 를 나머지라고 한다.
:::


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-Riemann_integral}

구간 $[a,\,b]$ 에서 정의된 함수 $f$ 를 생각하자. 수열 $\langle x_n\rangle$ 가 $x_1=a<x_2<\cdots <x_n=b$ 를 만족할 때,

$$
\begin{aligned}
&\lim_{n \to \infty} \sum_{k=2}^n \min(\{f(x_{i-1}),\, f(x_{i})\}) (x_{i}-x_{i-1})  \\
&\qquad \qquad \qquad = \lim_{n \to \infty} \sum_{k=2}^n \max(\{f(x_{i-1}),\, f(x_{i})\}) (x_{i}-x_{i-1})
\end{aligned} 
$$

라면 함수 $f$ 는 $[a,\,b]$ 구간에서 리만 적분 가능하다고 하며 위의 값을

$$
\int_{a}^b f \, dx
$$
라고 쓴다.

:::
:::

</br>

::: {#prp-continuous_function_integrable} 

$[a,\,b]$ 구간에서 연속인 함수는 리만 적분 가능하다.
:::

</br>

::: {#prp-first_fundamental_theorem_of_calculus}

#### 미적분학의 제 1 기본 정리 {#sec-1st_fundamental_theorem_of_calculus}

$f:[a,b] \to \mathbb{R}$가 리만 적분 가능한 함수일 때, 함수 $g : [a,\,b] \to \mathbb{R}$ 을 다음과 같이 정의하자.

$$
g(x) = \int_a^x f(t)\, dt.
$$

이 때, $g(x)$ 는 $(a,\,b)$ 에서 미분 가능한 함수이며 원래 주어진 함수 $f(x)$ 와는 다음의 관계를 만족힌다.

$$
\dfrac{d}{dx}g(x) = f(x).
$$

이 경우 $g(x)$ 를 $f(x)$ 의 **부정 적분(indefinite integral)** 이라 한다.
:::

</br>

::: {#prp-relation_betwein_indefinite_integral}

$f[a,\,b] \to \mathbb{R}$ 이 리만적분 가능한 함수이며, $a'\in [a,\,b]$ 라 하자. 이 때

$$
g(x) = \int_a^x f(t)\, dt,\qquad h(x) = \int_{a'}^x f(t)\, dt
$$

라고 하면, 

$$
g(x)-h(x) = \text{const}
$$

이다.

:::


</br>

::: {#prp-second_fundamental_theorem_of_calculus}

#### 미적분학의 제 2 기본 정리 {#sec-2nd_fundamental_theorem_of_calculus}

$[a,\,b]$ 구간에서 적분가능한 함수 $f(x)$ 의 부정적분이 $F(x)$ 일 때 다음이 성립한다.

$$
\int_a^b f(x)\, dx = F(b)-F(a).
$$

:::

</br>

::: {#prp-mean_value_theorem_for_integrals}
#### 적분에 대한 평균값 정리 (Mean value theorem for integrals) {#sec-mean_value_theorem_for_integrals}

함수 $f:X \subset\mathbb{R} \to \mathbb{R}$ 이 $[a,\,b]$ 를 포함하는 구간에서 에서 연속이면
$$
f(c) = \dfrac{1}{b-a}\int_a^b f(x),\,dx
$$

를 만족하는 $c\in (a,\,b)$ 가 존재한다.
:::

</br>


::: {#prp-weighted_mean_value_theorem_for_integrals}

#### 적분에 대한 가중 평균 정리 (Weighted mean value theorems for integrals) {#sec-weighted_mean_value_theorem_for_integrals}

함수 $f:X \subset\mathbb{R} \to \mathbb{R}$, $g:Y \subset\mathbb{R} \to \mathbb{R}$  이 $[a,\,b]$ 를 포함하는 구간에서 에서 연속이면
 
$$
\int_a^b f(x)\,g(x)\, dx = f(c)\int_a^b g(x)\, dx
$$

을 만족하는 $c\in (a,\,b)$ 가 존재한다.

:::

</br>

## 다변수 미적분학 정리 {#sec-summary_of_multy_variable_calculus}

::: {.callout-note appearance="simple" icon="false"}

::: {#def-n_cell}

#### $n$-cell

$\mathbb{R}^n$ 에서

$$
[a_1,\,b_1]\times \cdots \times [a_n,\,b_n] = \{(x_1,\ldots,\,x_n)\in \mathbb{R}^n : a_i \le x_i \le b_i,\, i=1,\ldots,n\}
$$

를 $n$-cell 이라고 한다.

::: 
:::

</br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-continuity_mv}

#### 다변수 함수의 연속

$\mathbb{R}^n$ 에서의 열린 집합 $U$ 에서 정의된 함수 $\boldsymbol{F}:U \to \mathbb{R}^m$ 이 

$$
\lim_{\boldsymbol{h} \to \boldsymbol{0}} \|\boldsymbol{F}(\boldsymbol{p} + \boldsymbol{h}) - \boldsymbol{F}(\boldsymbol{p})\|  = 0
$$

일 때 $\boldsymbol{F}$ 는 $\boldsymbol{p}$ 에서 **연속** 이라고 한다. $\boldsymbol{F}$ 가 모든 $\boldsymbol{p}\in U$ 에서 연속일 때 $\boldsymbol{F}$ 를 $U$ 에서 연속이라고 한다.

:::
:::

</br>  


::: {.callout-note appearance="simple" icon="false"}
::: {#def-differentiation_mv}

#### 다변수 함수의 미분과 자코비 행렬

$\mathbb{R}^n$ 에서의 열린 집합 $U$ 에서 정의된 함수 $\boldsymbol{F}:U \to \mathbb{R}^m$ 이 $\boldsymbol{p}\in U$ 에서 어떤 행렬 $M\in \mathcal{M}_{m \times n}(\mathbb{R})$ 에 대해

$$
\lim_{\boldsymbol{h} \to \boldsymbol{0}} \dfrac{\|\boldsymbol{F}(\boldsymbol{p} + \boldsymbol{h}) - \boldsymbol{F}(\boldsymbol{p}) - \boldsymbol{Mp}\|}{\|\boldsymbol{h}\|} = \boldsymbol{0}
$$

를 만족 할 때 $\boldsymbol{F}$ 는 $\boldsymbol{p}$ 에서 미분가능하다 라고 한다. 이때 $\boldsymbol{M}$ 을 $\boldsymbol{p}$ 에서의 $\boldsymbol{F}$ 의 **자코비 행렬(Jacobian matrix)** 이라고 하며 $D\boldsymbol{F}(\boldsymbol{p}),\, \boldsymbol{J}_\boldsymbol{F}(\boldsymbol{p})$ 옥은 $\boldsymbol{F}'(\boldsymbol{p})$ 라고 표기한다. $\boldsymbol{F}$ 가 모든 $\boldsymbol{p}\in U$ 에서 미분 가능일 때 $\boldsymbol{F}$ 를 $U$ 에서 미분가능하다 라고 한다.

:::
:::

</br>

::: {#prp-equivalence_of_differentiation_for_mv}

$\mathbb{R}^n$ 에서의 열린 집합 $U$ 에서 정의된 함수 $\boldsymbol{F}:U \to \mathbb{R}^m$ 에 대해 다음은 동치이다.

&emsp; ($1$) $\boldsymbol{F}$ 는 $\boldsymbol{p}\in U$ 에서 미분가능하다.

&emsp; ($2$) 어떤 $\boldsymbol{M}\in \mathcal{M}_{m \times n}(\mathbb{R})$ 과 $\displaystyle \lim_{\boldsymbol{h}\to \boldsymbol{0}}\dfrac{\boldsymbol{R}(\boldsymbol{h})}{\|\boldsymbol{h}\|} = \boldsymbol{0}$ 인 어떤 함수 $\boldsymbol{R}:U \to \mathbb{R}^m$ 에 대해 
$$
\boldsymbol{F}(\boldsymbol{p}+\boldsymbol{h}) = \boldsymbol{Mp}+\boldsymbol{R}(\boldsymbol{v})
$$ 
&emsp; &emsp; 이다. 

:::

</br>

::: {#thm-directional_derivative}

$\boldsymbol{F} : U\subset \mathbb{R}^n \to \mathbb{R}^m$ 가 $\boldsymbol{p}\in U$ 에서 미분가능할 때 임의의 $\boldsymbol{u}\in \mathbb{R}^n-\{\boldsymbol{0}\}$ 에 대해 아래의 극한이 존재한다.

$$
\lim_{t \to \infty} \dfrac{\boldsymbol{F}(\boldsymbol{p}+t\boldsymbol{u}) - \boldsymbol{F}(\boldsymbol{p})}{t}
$$ {#eq-directional_derivative}

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-partial_derivative}

#### 방향미분과 편미분
$\boldsymbol{u}$ 가 단위벡터, 즉 $\|\boldsymbol{u}\|=1$ 일 때 @eq-directional_derivative 의  극한을 $\boldsymbol{F}$ 의 $\boldsymbol{p}$ 에서의 $\boldsymbol{u}$ 방향으로의 **방향미분 (directional derivative)** 라고 하고 $D_\boldsymbol{u}\boldsymbol{F}(\boldsymbol{p})$ 라고 쓴다. $\boldsymbol{u}$ 가 어떤 표준기저 $\hat{\boldsymbol{e}}_i$ 일 때의 방향미분을 **편미분 (partial derivative)** 라고 하며 $D_{\hat{\boldsymbol{e}}_i} \boldsymbol{F}(\boldsymbol{p})$ 를 $D_i \boldsymbol{F}(\boldsymbol{p})$, $\dfrac{\partial \boldsymbol{F}}{\partial x_i}(\boldsymbol{p})$, 혹은 $\partial_i \boldsymbol{F}(\boldsymbol{p})$ 라고 표기한다. 

:::
:::

</br>

::: {#prp-differentiable_continuous}

$\boldsymbol{F} : U \subset \mathbb{R}^n \to \mathbb{R}^m$ 이 $\boldsymbol{p}\in U$ 에서 미분가능이면 $\boldsymbol{p}$ 에서 연속이다.

:::

</br>

## 이 책에 사용할 행렬 표기의 규칙들 {#sec-transcription_ruls}

수학과 프로그래밍 전체에서 행렬이 많이 사용된다. 여기서 행렬을 표현하는 데 사용한 몇가지 규칙을 나열한다. **(J-3)** 과 같은 항목은 Julia 의 규칙이며 **(M-2)** 와 같은 항목은 수학적인 표현에 대한 규칙이다. 두 표현의 번호가 같은 경우는 수학적인 표현에 대한 Julia 구현에 대한 규칙 혹은 설명을 의미한다.

**(J-0)** 특별한 언급이 없을 경우 Julia 에서 정수형과 실수형은 각각 `Int64`, `Float64` 를 사용한다. 

**(J-1)** 기본적으로 코드상에서 행렬은 `A, B` 와 같은 대문자 혹은 `A1` 과 같은 대문자로 시작하는 변수명을 사용한다. Julia 에서 행렬 `A` 의 $i$ 번째 행벡터는 `A[i,:]` 로, $j$ 번째 열벡터는 `A[:,j]` 로 표현 할 수 있으므로 그대로 사용한다. 행렬 `A` 의 $i$ 행 $j$ 열 성분은 `A[i, j]` 이다. 벡터와 스칼라는 `x`, `y`, `a`, `b` 와 같은 소문자나 `x_effective`, `b2` 와 같이 소문자로 시작하는 변수명을 사용한다. `x` 가 벡터인 경우 $i$ 번째 성분은 `x[i]` 이다.


**(J-2)** 행렬 `A` 에 대한 전치행렬은 `transpose(A)`, 수반행렬은 `A'` 나 `adjoint(A)` 로 얻을 수 있다.

**(J-5)** Julia 에서는 Matlab의 `eye()` 나 numpy 의 `np.identity()` 혹은 `np.eye()` 와 같은 $n\times n$ 항등행렬을 위한 함수가 존재하지 않는다. 대신 `LinearAlgebra` 모듈의 uniform scaling operator `I` 를 임의의 크기와 임의의 원소 타입의 항등행렬로 사용할 수 있다. 타입과 크기는 다른 행렬과 계산할하는 등 필요할 때 정해진다. 

```txt
In [1]: I+[2 3;4 2]
Out[1]: 2×2 Matrix{Int64}:
 3  3
 4  3

In [2]: I-[1 2 3;3 4 5; 6 7 8]
Out[2]: 3×3 Matrix{Int64}:
  0  -2  -3
 -3  -3  -5
 -6  -7  -7
```

필요할 경우에는 항등행렬을 아래와 같이 type을 직접 선언하여 만들 수 있다.

```julia
Matrix{Int32}(I, 3, 3)      # Int32 타입의 3x3 항등행렬
Matrix{Float64}(I, 5, 5)    # Float64 타입의 5x5 항등행렬
Matrix{Bool}(I, 4, 4)       # Bool 타입의 4x4 항등행렬
```

$\mathbb{R}^{5 \times 1}$ 의 단위행렬 $\boldsymbol{e}_3$ 는 다음과 같이 얻을 수 있다.

```julia
e_3 = Matrix{Float64}(I, 5, 5)[:,3]
```

**(M-6)** $m\times n$ 행렬 $\boldsymbol{A}$ 와 $m \times k$ 행렬 $\boldsymbol{B}$ 에 대해(두 행렬의 행의 갯수가 같음에 주의하라)) $[\boldsymbol{A}\; \boldsymbol{B}]$ 는 $\boldsymbol{A}$ 행렬 옆에 $\boldsymbol{B}$ 행렬을 두는 $m \times (n+k)$ 행렬을 의미한다. $m\times n$ 행렬 $\boldsymbol{A}$ 와 $l \times n$ 행렬 $\boldsymbol{C}$ 에 대해 (두 행렬의 열의 갯수가 동일함에 유의하라) $[\boldsymbol{A} \,; \boldsymbol{C}]$ 는 $\boldsymbol{A}$ 행렬 아래에 $\boldsymbol{C}$ 행렬을 두는 $(m+l)\times n$ 행렬이다. 아마 $\begin{bmatrix} \boldsymbol{A} \\ \boldsymbol{C} \end{bmatrix}$ 와 동일하다고 하면 이해하기 쉬울 것이다. `;` 기호는 julia 에서 열바뀜을 나타내므로 julia 와 어느정도 유사성이 있다 하겠다. 여기에 $l\times k$ 행렬 $\boldsymbol{D}$ 에 대해 $\begin{bmatrix} \boldsymbol{A} & \boldsymbol{B} \\ \boldsymbol{C} & \boldsymbol{D} \end{bmatrix}$ 가 의미하는 것은 여러분이 쉽게 유추 할 수 있을 것이다.

**(J-6)** Julia 에서는 다음과 같이 사용 할 수 있다.

```text
julia> A = [1 3;2 4];B=[3 2; 4 3];[A B]
2×4 Matrix{Int64}:
 1  3  3  2
 2  4  4  3
```

**(M-7)** $m\times n$ 행렬 $\boldsymbol{A}$ 와 $m \times k$ 행렬 $\boldsymbol{B}$ 혹은 $m$ 차원 벡터 $\boldsymbol{b}$ 에 대해 $[\boldsymbol{A} \mid \boldsymbol{B}]$ 혹은 $[\boldsymbol{A} \mid \boldsymbol{b}]$ 는 행렬에 대한 연산을 동시에 적용하기 위한 개념이다. 연산 $\hat{L}[\boldsymbol{A} \mid \boldsymbol{B}] = [\hat{L}\boldsymbol{A} \mid \hat{L}\boldsymbol{B}]$ 를 의미한다.

</br>
