---
title: "푸리에 변환을 이용한 이미지 처리"

number-sections: true
number-depth : 3
crossref:
  chapters: false
---

{{< include ../../latexmacros.qmd >}}

</br>

## 푸리에 급수와 푸리에 변환의 수학적 성질


### 푸리에 급수
주기 $T$ 를 갖는 연속함수 $f(t)$ 는 다음과 같은 푸리에 급수로 표현 할 수 있다.

$$
\begin{aligned}
f(t) &= \sum_{n=-\infty}^{\infty} F_n \exp \left(\dfrac{i 2\pi n}{T}t\right)\,,\\
F_n &= \dfrac{1}{T}\int_{-T/2}^{T/2} f(t) \exp \left(-\dfrac{i2\pi n }{T}t \right)\, dt\,, \qquad n\in \mathbb{Z}
\end{aligned}
$$ {#eq-ImageProcessing_fourier_expansion}

<br>

### 기저함수의 직교성 {#sec-ImageProcessing_orthogonality_of_fourier_basis}

$$
\int_{-T/2}^{T/2} \exp \left( \dfrac{i 2\pi m}{T}t\right) \exp \left(-\dfrac{i 2\pi n}{T}t \right)\, dt = \delta_{nm}
$$ {#eq-ImageProcessing_orthogonality_of_fourier_basis}

<br>

### 주기함수와 푸리에 급수

- 모든 주기성을 갖는 연속함수는 푸리에 급수로 표현 할 수 있다.

</br>

## 푸리에 변환

### 1차원 푸리에 변환
$$
\begin{aligned}
F(\mu) &= \mathfrak{I} \left[f(t)\right]=\int_{-\infty}^{\infty} f(t)e^{-2i\pi \mu t}\, dt\,, \\
f (t) &= \mathfrak{I}^{-1} \left[F(\mu)\right] = \int_{-\infty}^{\infty} F(\mu) e^{2i \pi \mu t} \, d\mu
\end{aligned}
$$



### 2차원 푸리에 변환
$$
\begin{aligned}
F(u,\,v) &= \mathfrak{I} \left[f(x,\,y)\right]=\int_{-\infty}^{\infty}\int_{-\infty}^{\infty} f(x,\,y)e^{-2i\pi (ux+vy)}\, dxdy\,, \\
f (x,\,y) &= \mathfrak{I}^{-1} \left[F(u,\,v)\right] = \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} F(\mu) e^{2i \pi (ux+vy)} \, dudv
\end{aligned}
$$

<br>

### 푸리에 변환의 몇가지 수학적 성질

#### **1. Similarity**

$$
f (x,\,y) \iff F(u,\,v) \implies f(ax,\,by) =\dfrac{1}{ab} F\left(\dfrac{u}{a},\, \dfrac{v}{b}\right)
$$


---

$$
\begin{aligned}
\mathfrak{I}[f(ax,\,by)] &= \iint f(ax,\, by) e^{-2i\pi (ux+vy)}\,dxdy \qquad & t=ax,\, s=by\\
&= \dfrac{1}{ab} \iint f(s,\,t) e^{-2i \pi (ut/a+vs/b)}\, dtds \\
&= \dfrac{1}{ab} F \left(\dfrac{u}{a},\, \dfrac{v}{b} \right)
\end{aligned}
$$

<br>

#### **2. Shift Theorem**

$$
f(x,\,y) \iff F(u,\,v) \implies f(x-a,\, y-b) \iff \exp (i2\pi (au+bv)) F(u,\,v)
$$

---

$$
\begin{aligned}
\mathfrak{I}[f(x-a,\, y-b) ]&= \iint f(x-a,\, y-b) e^{-2i\pi (ux+vy)} \,dxdy \qquad & t=x-a,\, s=y-b\\
&=\iint f(t,\,s) e^{-2i\pi (ux+vy)} e^{2i\pi (au+bv)} \, dxdy \\
&= e^{2i\pi (au+bv)}F(u,\,v)
\end{aligned}
$$

<br> 

#### **3. 도함수의 푸리에 변환**

$$
\mathfrak{I}[f(x)] = F(u)   \implies \mathfrak{I}\left[ \dfrac{d^kf}{dx^k} \right] =( 2i\pi u)^k F(u) 
$$

---
$k=1$ 인 경우만 보이면 나머지는 쉽게 일반화 된다. $\mathfrak{I}[f(x)]=F(u)$ 이면 $f(x)=\displaystyle \int_{-\infty}^{\infty} F(u)e^{2i\pi ux}\, du$ 이므로

$$
f'(x) =  \int_{-\infty}^{\infty}(2i\pi u) F(u)e^{2i \pi ux} \, du
$$

이다. 따라서 

$$
\mathfrak{I}[f'(x)] = (2i\pi u) F(u)
$$
이다.

</br>

### Fourier Spectrum, Phase, Fourier Power Spectrum

$F(u,\,v)$ 를 극좌표 형태로 다음과 같이 표현 할 수 있다. 

$$
F(u,\,v) = |F(u,\,v)| e^{i\Phi(u,\,v)}
$$


이 때 $|F(u,\,v)|$ 를 **푸리에 스펙트럼 (Fourier spectrum)** 이라 하고, $\Phi(u,\,v)$ 를 **위상 (phase)** 이라 한다. 또한 $P(u,\,v) =|F(u,\,v)|^2$ 를 **푸리에 파워 스펙트럼 (Fourier power spectrum)** 이라 한다.

</br>

### 평행이동과 회전변환의 푸리에 변환


</br>

### 주기적 임펄스 함수의 푸리에 변환

단위 임펄스 함수(디렉 델타 함수)가 $T$ 를 주기로 반복되는 함수를 주기적 임펄스 함수라 하며 이를 $S_T(t)$ 라 하자. 이는 주기함수이므로 푸리에 급수로 표현 할 수 있으며 다음과 같다. 

$$
\begin{aligned}
S_T(t) &= \sum_{n=-\infty}^{\infty} \delta \left(t-nT \right) \,, \\
&=\dfrac{1}{T} \sum_{n=-\infty}^{\infty} \exp \left( \dfrac{-i2n\pi t}{T}\right)
\end{aligned}
$$

단일 임펄스 함수 $\delta(\mu-\mu_0)$ 에 대한 푸리에 변환은 다음과 같다.

$$
\mathfrak{I}[\delta (\mu-\mu_0)] = \int_{-\infty}^{\infty} \delta (\mu-\mu_0) e^{2i\pi \mu t}\, d\mu = e^{2i\pi \mu_0 t}
$$

따라서,

$$
\mathfrak{I}^{-1} \left[ \delta \left( \mu-\dfrac{n}{T} \right) \right] = \exp \left( \dfrac{2in\pi t}{t} \right) \iff \mathfrak{I}\left[  \exp \left( \dfrac{2in\pi t}{t} \right) \right] =  \delta \left( \mu-\dfrac{n}{T} \right)
$$

이다. 이를 이용하면 $s_T(t)$ 의 푸리에 변환식 $S(\mu)=\mathfrak{I}[s_N(t)]$ 를 계산 할 수 있으며 다음과 같다.

$$
S (\mu) = \mathfrak{I}\left[\dfrac{1}{T} \sum_{n=-\infty}^{\infty} \exp \left( \dfrac{-i2n\pi t}{T}\right)\right] = \dfrac{1}{T} \sum_{n=-\infty}^{\infty} \mathfrak{I}\left[ \exp \left( \dfrac{-i2n\pi t}{T}\right) \right] = \dfrac{1}{T} \sum_{n=-\infty}^{\infty} \delta \left(\mu - \dfrac{n}{T}\right)
$$

</br>

## Convolution 의 푸리에 변환

두 함수 $f(t),\, g(t)$ 의 convolution  $f(t) \ast g(t)$ 은 다음과 같이 정의된다.

$$
f(t) \ast g(t) \equiv \int_{-\infty}^{\infty} f(\tau) g(t-\tau) \, d\tau
$$

$F(\mu)= \mathfrak{I}[f(t)],\, G(\mu)=\mathfrak{I}[g(t)]$ 라 할 때, $f(t)\ast g(t)$ 의 푸리에 변환을 구하면,

$$
\begin{aligned}
\mathfrak{I}[f(t) \ast g(t)] &= \int_{-\infty}^{\infty} \left[ \int_{-\infty}^{\infty} f(\tau)g(t-\tau) d\tau\right] e^{-2in\pi \mu t}\, dt \\
&= \int_{-\infty}^{\infty}f(\tau) \left[  \int_{-\infty}^{\infty} g(t-\tau)e^{-2in \pi \mu t}\, dt\right] \,d\tau \\
&= \int_{-\infty}^{\infty} f(\tau) G(\mu)e^{-2in \pi \mu \tau} \, d\tau \\
&= F(\mu)G(\mu)
\end{aligned}
$$


즉 합성곱의 푸리에 변환은 푸리에 변환의 곱이다. 이를 응용하면 두 함수의 곱의 푸리에변환은 합성곱이 됨을 보일 수 있다. 즉,

$$
\mathfrak{I}[f(t)g(t)]=F(\mu)\ast G(\mu)
$$

가 된다.

</br>

## 푸리에 변환과 샘플링 (sampling)

### 샘플링
임의의 연속함수 $f(t)$ 를 $T$ 를 주기로 샘플링 하였다고 하자. 그렇다면 이 샘플링 $\tilde{f}(t)$ 은 다음과 같은 식으로 표현 할 수 있다.

$$
\tilde{f}(t) = f(t)S_T(t)\sum_{n=-\infty}^{\infty} f(t) \delta (t-nT)
$$

즉 연속 신호에 대해 주기적으로 신호를 뽑아 불연속 신호로 만드는 것을 **sampling** 이라 한다. 

<br>

### 샘플링 된 신호의 푸리에 변환

이 때 $\mathfrak{I}[f(t)]= F(\mu),\, \mathfrak{I}[s_T(t)]= S(\mu)$ 라 하자 $\displaystyle S(\mu)=\dfrac{1}{T} \sum_{n=-\infty}^{\infty} \delta \left( \mu - \dfrac{n}{T}\right)$ 임은 알고 있다. 그렇다면 $\tilde{F}(\mu)=\mathfrak{I}\left[\tilde{f}(t) \right]$ 를 구하면,

$$
\begin{aligned}
\tilde{F}(\mu) & = F(\mu)\ast S(\mu) = \int_{-\infty}^{\infty} F(\tau)S(\mu-\tau)\, d\tau \\
&= \dfrac{1}{T} \sum_{n=-\infty}^{\infty}\int_{-\infty} F(\tau) \delta \left(\mu-\tau-\dfrac{n}{T}\right)\, d\tau \\
&= \dfrac{1}{T}\sum_{n=-\infty}^{\infty} F\left( \mu - \dfrac{n}{T} \right)
\end{aligned}
$$

이다. 즉, 주기 $T$ 로 샘플링된 연속 함수 $f(t)$의 함수의 푸리에 변환은 원래 함수의 푸리에 변환 $F(\mu)$ 를 주기 $1/T$ 를 갖는 임펄스 함수로 바꾼 형태임을 알 수 있다.

</br>

### 밴드-한계 신호 (band-limited signal), Over-sampling, under-sampling, critical-sampling, aliasing

- 위의 그림을 보자. 원본연속함수(연속신호) $f(t)$ 를 푸리에 변환한 함수 중, 그래프 (a) 와 같이 일부 구간 $[-\mu_M,\,\mu_M]$에 대한 변환 신호 $F(\mu)$ 만을 알고 있는 상황이라고 가정하자. 이렇계 특정 구간을 제외하고 $F(\mu)=0$ 일 때 이를 밴드한계신호라 한다.

- $f (t)$ 를 주기 $T$ 를 조절해 가며 샘플링한 함수를 푸리에 변환한다고 하자. 만약, 주기를 $1/T>2\mu_M$ 이 되도록 샘플링하면 $F(\mu)$ 가 주기적으로 배열되며 그간격은 $1/T$ 가 이되겠지만, $1/T>2\mu_M$ 이므로, 결과는 그림 (b) 와 같이 띄엄띄엄 배열된 삼각형 신호가 될 것이다. 즉 $\tilde{F}(\mu)$ 가 불연속 함수가 된다. 그러나 원래 $F(\mu)$ 가 가지고 있던 함수정보가 고스란히 남아 있으므로, 결과물로 부터 다시 역변환을 취하면 원래 함수 (신호값) 을 복원 할 수 있다. 이러한 결과를 **오버-샘플링 (over-sampling)** 이라 한다.

- 만약, 주기 조건이 $1/T < 2\mu_M$ 이라면 이번에도 $F(\mu)$ 가 주기적으로 배열되겠지만, $1/T < 2\mu_M$ 이므로, 결과는 그래프 (d) 처럼 삼각형 신호 중 일부가 파묻힌 결과가 될 것이다. 비록 $F(\mu)$ 는 연속 함수가 되었지만, 원래의 정보를 잃어 버리게 되며, 이러한 결과를 **언더-샘플링 (under-sampling)** 이라 한다.

- 만약 주기가 $1/T= 2\mu_M$ 로서 딱 맞다면, 그림 (c) 처럼, $F(\mu)$ 는 삼각형 신호가 제대로 연속 배열된 결과가 된다. 이러한 결과를 **critical-sampling** 이라 한다.

- 따라서 원래 함수의 신호를 복원하기 위한 샘플링 충분 조건은 $1/T\ge 2\mu_M$ 이 될 것이다. 이것은 소위 나이퀴스트-샤논 샘플링 정리의 결과이다.

- 이 정리에 따르면, 어떤 신호든 밴드-한계 함수가 그 함수의 샘플들로부터 복원되기 위해서는, 샘플링 주기의 역수$1/T$ 가 샘플링된 밴드의 최대값의 두 배보다 커야 한다. 만약, 주기의 역수가 이 조건을 만족시키지 못한다면 (즉, 언더-샘플링된 상황), 복원된 신호는 완벽하지 않을 것이며, 이러한 상황을 **주파수 앨리어싱 (frequency aliasing)** 혹은 그냥 **앨리어싱** 이라고 한다.

- 앨리어싱은 주로 원래 이미지의 해상도보다 낮은 해상도로 이미지를 샘플링하거나, 이미지 획득 장치의 샘플링 간격이 피사체 자체의 고유 구조 특징보다 더 클 때 발생합니다.

</br>
# 4.3 이산 푸리에 변환 (Discrete Fourier Transformation, DFT)

1차원 공간상의 함수 $f$ 에 대해 $k$ 번째 에서의 값을 $f_k$ 라 하자. 그리고 이 수열을 $\mathbf{f}$ 라 하자. 즉,
$$
\mathbf{f}=(f_0,\ldots,\,f_{N-1})
$$

이다.

우리는 여기서 한가지 가정을 하게 되는데 $f$ 이 주기 $N$ 을 갖는다는 것이다. 즉 $f_{k+N}=f_k$ 이다. 이 때 $\mathfrak{I}[\mathbf{f}]=\mathbf{F}=[F_1,\ldots,\,F_{N-1}]$ 의 $F_\mu$ 는 다음과 같이 구할 수 있다.

$$
F_\mu = \dfrac{1}{N}\int_{0}^{N-1} f(t) \exp \left(-\dfrac{i2\pi \mu }{N}t \right)\, dt = \dfrac{1}{N} \sum_{k=0}^{N-1} f_i \exp\left(-\dfrac{i2\pi \mu }{N} k \right)
$$

또한 $f_k$ 는 다음과 같이 표현 할 수 있다.

$$
f_k = \sum_{\mu=0}^{N-1} F_\mu \exp \left(-\dfrac{i2\pi k\mu }{N} \right)
$$


## 이차원 이산 푸리에 변환

$$
\begin{aligned}
F_{uv} &= \dfrac{1}{MN} \sum_{j=0}^{M-1}\sum_{k=0}^{N-1} f_{jk} \exp \left[-2i\pi \left(\dfrac{ju}{M}+\dfrac{kv}{N}\right)\right] \\
f_{jk} &=  \sum_{j=0}^{M-1}\sum_{k=0}^{N-1} F_{uv} \exp \left[2i\pi \left(\dfrac{ju}{M}+\dfrac{kv}{N}\right)\right]
\end{aligned}
$$

<br>

### 연속 푸리에 변환과의 관계에서 보는 DFT 의 성질.

<br>

#### **주기성**

연속 푸리에 변환은 앞서 보았듯이 아래와 같다. 

$$
\begin{aligned}
F(u,\,v) &= \mathfrak{I} \left[f(x,\,y)\right]=\int_{-\infty}^{\infty}\int_{-\infty}^{\infty} f(x,\,y)e^{-2i\pi (ux+vy)}\, dxdy\,, \\
f (x,\,y) &= \mathfrak{I}^{-1} \left[F(u,\,v)\right] = \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} F(\mu) e^{2i \pi (ux+vy)} \, dudv
\end{aligned}
$$

불연속 푸리에 변환쌍 에서는 $x, y$ 대신 $x/N, y/M$가,그리고 $u,v$  대신 $u/N, v/M$ 가 쓰였다. 이는 원본 함수가 정해진 구간 $x = 0,\,1,\ldots,\,N-1$ 혹은 $y=1,\ldots,\,M-1$ 을 벗어나면 다시 주기 $N, M$ 을 가지고 모든 1차원 공간에서 반복된다는 가정이 내포되어 있다. 즉,
정수 $p,\,q$ 에 대해

$$
\begin{aligned}
f(x+pN,\, y+qN) &= f(x,\, y) \\
F(u+pN,\, v+qN) &= F(u,\, v)
\end{aligned}
$$
가 성립한다는 뜻이다.

<br>

#### **정규화 인자 (normalization factor)**

또한, $F(u,\,v)$ 의 계수에 연속 푸리에 변환에는 없던 $\dfrac{1}{NM}$ 가 생긴것을 볼 수 있다.우리가 다루는 이미지 같은 신호는 공간상에서 제약이 있고 (즉, 가로와 세로의 길이가 정해져 있고), 또한 신호들은 불연속적으로 나열되어 있으므로, 이를 푸리에 변환 과정에서 보상하기 위해, $F (u,\,v)$ 의 계수에 $\dfrac{1}{MN}$ 가 정규화 인자 (normalization factor)로서 생긴 것이다.


</br>

## 2차원 불연속 푸리에 변환 (2D DFT)을 이용한 이미지 처리

</br>

### Ideal Low Pass Filtering

2D DFT 행렬을 DC 인자를 중앙에 배치하여 재배열했을 경우, 원본 이미지에서 낮은 픽셀 빈도를 갖는 성분은 중앙 (즉, $(u,v) \approx (0,0)$) 근처 에 모이게 된다. 낮은 빈도를 갖는다는 것은 공간 상에서 신호 주기가 크다는 의미고, 역공간에서는 ‘1/주기’가 작은 값으로 대응이 될 것이므로, $(u, v)$ 가 중앙 부분으로 몰리게 되는 것이다. 따라서, 원본 이미지의 로우-패스 필터링을 하고 싶다면, 푸리에 변환 된 행렬의 중앙 부분만 따로 골라내어 다시 역변환하면 될 것이다.

가장 간단히 생각 할 수 있는 방법은 원점 주위의 특정 반경 안에 들어오는 2D DFT 이미지만 뽑아 역변환 해주는 것이며 이를 ideal low pass filtering 이라 한다.

</br>

### Ideal High Pass Filtering

Ideal low pass filtering 과 반대로 생각해 주면 된다. 

</br>

### 버터워스 필터링 (Butterworth filtering)

Ideal low/high pass filter 는 계단 함수 형태로, 그 과정에서 물결무늬 같은 원하지 않는 패턴이 생성된 것도 확인할 수 있었다. 이러한 부작용을 방지하기 위해 컷오프 거리를 기준으로 로우-패스 혹은 하이-패스 영역을 설정하는 방식을 계단 함수가 아닌, 조금 더 부드러운 연속 함수로 바꿀 수 있다. 그중 하나가 버터위스 필터링으로 다음과 같이 정의된다.

$$
\begin{aligned}
\text{Low pass filter } h(u,\,v) &= \dfrac{1}{1+\left( 1+\dfrac{(u^2+d^2)^{1/2}}{D} \right)^{2n}} \\
\text{High pass filter } h(u,\,v) &= \dfrac{1}{1+\left(1+\dfrac{D}{(u^2+d^2)^{1/2}}\right)^{2n}} 
\end{aligned}
$$


</br>

### Gaussian Filtering

</br>

### 위상 보존 필터 (zero-phase-shift filter), 위상 비보존 필터 (Nonzero-phase-shift filter)

우리는 지금까지 원본 이미지 $f(x,\,y)$의 역공간 $F(u,\,v)$ 에서 작업해 왔다. $F(u,\,v)$ 는 복소함수로 실수부 $R(u,\,v)$ 와 허수부 $I(u,\,v)$ 가 존재하여 $F(u,\,v) = R(u,\,v) +iI(u,\,v)$ 이다. 이 때 $\arctan \left( \dfrac{I(u,\,v)}{R(u,\,v)}\right)$ 를 $F(u,\,v)$ 의 위상이라고 한다. 

만약 어떤 필터에 의해 위상이 변하지 않는다면 이를 **위상 보존 필터**라 하고, 그렇지 않다면 **위상 비보존 필터** 라 한다.

</br>

### 밴드삭제 필터링, 놋치 필터링.

</br>

### Periodic noise reduction - Bragg filtering

</br>

### Deblurring using inverse filtering

잘 안됨... 더 알아 봐야 할 듯..